server {
    listen 80;
    server_name 34.71.114.198;

    # Support for hardcoded /zeebull/ prefix in user frontend
    location /zeebull/ {
        alias /var/www/zeebull/;
        index index.html;
        try_files  / /index.html;
    }

    # API Uploads
    location /uploads/ {
        alias /var/www/zeebull/ResortApp/uploads/;
        expires 7d;
        add_header Cache-Control 'public';
    }

    # User Frontend (Root)
    location / {
        root /var/www/zeebull;
        index index.html;
        try_files  / /index.html;
    }

    # zeebulladmin
    location /zeebulladmin/ {
        alias /var/www/zeebull/zeebulladmin/;
        index index.html;
        try_files  / /zeebulladmin/index.html;
    }

    # zeebullapi
    location /zeebullapi/ {
        proxy_pass http://localhost:8013/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade ;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host System.Management.Automation.Internal.Host.InternalHost;
        proxy_cache_bypass ;
        proxy_set_header X-Real-IP ;
        proxy_set_header X-Forwarded-For ;
        proxy_set_header X-Forwarded-Proto ;
        
        # Remove /zeebullapi/ from path when forwarding to API
        rewrite ^/zeebullapi/(.*) / break;
    }

    # API docs and other direct API access (if needed)
    location /api/ {
        proxy_pass http://localhost:8013/api/;
        proxy_http_version 1.1;
        proxy_set_header Host System.Management.Automation.Internal.Host.InternalHost;
        proxy_set_header X-Real-IP ;
    }
}
