"""add_server_defaults_to_branches

Revision ID: dd693127a8a5
Revises: 45a9e2352524
Create Date: 2026-03-18 10:30:49.158495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""add_server_defaults_to_branches

Revision ID: dd693127a8a5
Revises: 45a9e2352524
Create Date: 2026-03-18 10:30:49.158495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd693127a8a5'
down_revision: Union[str, Sequence[str], None] = '45a9e2352524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add server-side defaults and make columns NOT NULL
    op.alter_column('branches', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.text('true'))
    op.alter_column('branches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               server_default=None)
    op.alter_column('branches', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=None)
    # ### end Alembic commands ###

